server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${ip}:3306/UserDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Qwer13579
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
      enabled: true

ip: localhost

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

    banner: false

file:
  parent-path: ./file



logging:
  file:
    path: ./logs